### ISSUE TITLE
Got thrown out to main menu when marking bucket wheel excavators

### ISSUE THREAD

**Issue by Be-Cool-Man** [LuziferSenpai/Empty-Miner-Tool#2]
The following message appears when i mark an empty [Bucket Wheel Excavator](https://mods.factorio.com/mod/BigDrills)

    **Notice**
    
    Error while running event Empty_Miner_Tool::on_player_selected_area (ID 49)
    LuaEntity doesn't contain key 1.
    stack traceback:
    	__Empty_Miner_Tool__/control.lua:39: in function <__Empty_Miner_Tool__/control.lua:3>

After clicking the OK button, i get thrown into the main menu.

**Comment by LuziferSenpai** [comment]
Fixed.

**Comment by Be-Cool-Man** [comment]
Thank you for your quick response. Will test it out and give feedback, when finished.

**Comment by Be-Cool-Man** [comment]
Tests are finished. I didn't find bugs, but a minor inconvenience: 

— Setup —
→ Two drills feeding into one chest
→ One drill is empty, the other is not

— What to do —
→ Mark both drills with your marking tool

— Result —
→ The empty drill AND the chest gets marked for deconstruction

— Expected behaviour —
→ The empty drill gets marked for deconstruction
→ The chest doesn't get marked because there is an active drill feeding into it


«Edit: spelling/orthography»
